---
server :
  port : 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IshwarKhandelwal/spring-cloudconfig-server.git
          #username: uname
          #password: password
          search-paths:
          - 'station*'
          repos:
            perf:
            pattern:
             - '*/perf'
            uri : https://github.com/IshwarKhandelwal/spring-cloudconfig-server-perf.git
            search-paths:
            -  'station*'
            